YAPP-Github/21st-ALL-Rounder-Team-2-BE

- src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/main/java/com/yapp/artie/domain/user/controller/UserController.java
- src/main/java/com/yapp/artie/domain/user/service/UserService.java
- src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
기존 회원가입된 유저가 다시 회원가입할 경우 예외를 던지게 구현했는데, 이미 회원가입된 유저가 다시 회원가입한다면,
id를 반환하도록 기능 수정
close #14
> 기존 사용자 등록 시 아이디를 반환

- src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
- src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Publication.java
- src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/main/java/com/yapp/artie/domain/user/controller/UserController.java
- src/main/java/com/yapp/artie/domain/user/service/UserService.java
- src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
전시 테스트 작성 및 전시 서비스 리팩토링
close #21 
- [ x] 전시 테스트 코드 작성
- [ x] userService#findById 내부로 예외 처리 로직 이동
- [ x] 전시 발행 기능, 예외 처리를 발행 객체 내부로 캡슐화
- [ x] 전시 서비스 메서드 추출, 메서드 이동
> 전시 테스트와 리팩터링

- src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
- src/main/java/com/yapp/artie/global/util/S3Utils.java
- src/main/resources/application-aws.yml
- 이미지 업로드 Presigned URL 발급 후 업로드 에러 버그 개선
- 다양한 시도 끝에, GeneratePresignedUrlRequest에 withContentsType을 설정해서는 안되며, 업로드시에는 PUT 메소드를 써야하고, 많은 스택오버플로우의 SignatureDoesNotMatch 에러시 해결법으로 제공되는 Secret Key의 특수문자 제거나 새로운 IAM Key 발급은 의미없는 해결방법임을 꺠달음
- 기타 가독성을 위한 /n 추가
close #30
> 이미지 업로드 Presigned URL 발급 후 업로드 에러 버그 개선

- .github/workflows/deploy-prod.yml
- .gitignore
- src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
- src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
- src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkThumbnailDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/ArtworkThumbnailDtoPage.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfo.java
- src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
- src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/main/java/com/yapp/artie/domain/s3/controller/S3Controller.java
- src/main/resources/application-aws.yml
- S3 Presigned URL 발급 API의 Path Parameter가 post ID임을 안내하도록 Swagger 수정
- S3 Presigned URL 발급 API의 Path Parameter에 대한 Validation 추가
- 작품 등록 API의 imageUri property가 S3 Presigned URL발급 후 반환되는 imageKey와 일치해야함을 안내하도록 Swagger 수정 
- 작품 등록 API의 tags property에 대해, 태그 ID 필드는 기존에 존재하는 태그를 등록할 경우에는 필수로 제공되어야함을 안내하도록 Swagger 수정
- 전시 상세 정보 API 추가
- 작품 목록 조회 API 추가
close #32
> 전시 상세정보 API, 작품 목록 API 개발 및 일부 Swagger 값 수정

- src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
- src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
- src/main/java/com/yapp/artie/domain/archive/domain/artwork/ArtworkContents.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkBatchRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkBatchResponseDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/UpdateArtworkRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/main/java/com/yapp/artie/domain/archive/service/TagService.java
- 작품 수정 API 개발
- 다중 작품 등록 API 개발 : 이미지 Key 리스트를 요청받아 각각의 작품으로 생성하는 API
- 전시 작품 생성 API Swagger API Response의 설명 수정
close #40
> 작품 수정, 다중 작품 등록 API 개발 및 일부 Swagger 값 수정

- src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
- src/main/java/com/yapp/artie/domain/archive/domain/artwork/ArtworkContents.java
- src/main/java/com/yapp/artie/domain/archive/domain/artwork/NullArtwork.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitResponseDto.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/main/java/com/yapp/artie/global/util/DateUtils.java
- src/test/java/com/yapp/artie/DateUtilTest.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
캘린더 페이지에서 월 단위로 전시를 조회하는 기능을 구현했습니다. 아래 데이터 구조의 배열 형태로 응답합니다.
```json
{
"year" : 2023,
"month" : 2,
"day" : 1,
"imageUri" : "....",
"isPublished" : true
}
```
close #37
> 캘린더 월별 작품 조회 기능 구현

- src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
- src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfoPage.java
- Page 객체에 담기지만 contents의 타입만 보이는 현상의 개선
- Page 객체에 contents의 타입이 잘 명세되어 보여지나, Page객체 자체까지 배열 타입으로 보이는 현상의 개선
close #65
> Swagger에서 Page객체에 담겨 반환됨을 정상적으로 명시

- src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
- src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
카테고리 순서 변경 로직이  카테고리 조회 쿼리에 order by에 의존적이도록 구현되어 있는데, 정작 order by가 존재하지 않아서 첫 테스트는 통과하고(처음에는 시퀀스가 정렬), 이후에는 변경이 안되는 버그를 수정 + 테스트 케이스 추가 
close #59
> 카테고리 순서 변경 테스트

- src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
- src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
카테고리 시퀀스 생성을 0부터 시작하도록 변경한다. 
close #82
> 카테고리 순서 변경 버그

- README.md
- src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
- src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
- src/main/java/com/yapp/artie/domain/archive/domain/exhibit/PinType.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoByCategoryDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoByCategoryDtoPage.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
- src/test/resources/application.yml
- 상단 고정 설정 API 추가
- 홈 화면 조회 API(전체, 카테고리)의 상단 고정 적용
- 홈 화면 조회 API 하나로 통합
- 카테고리별 전시 목록 조회 API 추가 : 카테고리 페이지의 전시 목록은 상단 고정이 반영되어서는 안되므로 별도의 API가 필요함
**자세한 내용, 리뷰 확인 부탁드립니다.**
close #72, #77
> 전시 상단 고정 기능 추가, 카테고리별 전시 목록 조회 API 추가

- src/main/java/com/yapp/artie/domain/archive/controller/ExhibitController.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalendarExhibitResponseDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CalenderQueryResultDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/ExhibitByDateResponseDto.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/main/java/com/yapp/artie/global/util/DateUtils.java
- src/main/resources/application-develop.yml
- src/test/java/com/yapp/artie/DateUtilTest.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
- 캘린더 페이지의 특정 월의 일자별 전시 목록 조회 API
- createdAt 기준 정렬되도록 변경
- 등록 오래된 순 -> 최신순으로 변경
- 해당 날짜의 전시 수 필드 및 관련 로직 추가
- 해당 전시의 post ID 필드 및 관련 로직 추가
- 캘린더 페이지의 특정 날짜의 전시 목록 조회 API 추가
- 카테고리별 전시 목록 반환 API URI 수정
- /post/post/category/{id}로 설정되어있는 버그 개선
- DateUtil내 메소드가 LocalDate가 아닌 LocalDateTime을 다루도록 수정
close #79 
close #87
> 캘린더 페이지 내 일자별 전시 목록 조회 API 수정, 특정 날짜 전시 목록 조회 API 추가 및 기타 버그 수정

- src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
- src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/main/java/com/yapp/artie/domain/notice/controller/NoticeController.java
- src/main/java/com/yapp/artie/domain/notice/domain/Notice.java
- src/main/java/com/yapp/artie/domain/notice/dto/NoticeDetailInfo.java
- src/main/java/com/yapp/artie/domain/notice/dto/NoticeDto.java
- src/main/java/com/yapp/artie/domain/notice/exception/NoticeNotFoundException.java
- src/main/java/com/yapp/artie/domain/notice/repository/NoticeRepository.java
- src/main/java/com/yapp/artie/domain/notice/service/NoticeService.java
- src/main/java/com/yapp/artie/domain/user/controller/UserController.java
- src/main/java/com/yapp/artie/domain/user/dto/response/UserThumbnailResponseDto.java
- src/main/java/com/yapp/artie/domain/user/service/UserThumbnailService.java
- src/main/java/com/yapp/artie/global/config/swagger/SwaggerConfig.java
- src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
- src/test/java/com/yapp/artie/domain/notice/service/NoticeServiceTest.java
- src/test/java/com/yapp/artie/domain/user/service/UserThumbnailServiceTest.java
마이페이지에 사용자의 썸네일 조회 기능과 공지사항 조회 기능을 구현했습니다. 참고로 공지사항 생성 로직은 제외했습니다.
close #36
> 마이 페이지 공지사항 기능 구현

- src/main/java/com/yapp/artie/domain/archive/controller/ArtworkController.java
- src/main/java/com/yapp/artie/domain/archive/dto/artwork/CreateArtworkRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/tag/CreateArtworkTagDto.java
- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
전시에 첫번째로 작품이 등록될 경우, 전시의 미완성 상태를 해제하도록 로직 추가(isPublished=true)
- 작품 등록 API 수정
- 다중 작품 등록 API 수정
- ArtworkService 의 메소드 코드의 위치 이동 ( 컨벤션에 따름 )
- ArtworkService에 대한 테스트코드 추가
close #80
> 첫번째 작품 등록시, 미완성 상태 해제 ( isPublished = true )

- src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/CreateExhibitRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfo.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostInfoDto.java
- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/UpdateExhibitRequestDto.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
- src/test/java/com/yapp/artie/domain/user/service/UserThumbnailServiceTest.java
전시 생성, 수정, 조회 로직에서 `전시 링크(attachedLink)`가  반환, 사용할 수 있도록 변경했습니다.
피그마 화면에서는 보이지 않지만, 윤선님에게 물어봤는데 전시 링크도 수정 가능하다고 해서 업데이트 로직에도 반영했습니다.
#78
> 전시 정보에 링크 정보 반영

- src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
- src/main/java/com/yapp/artie/domain/archive/repository/TagRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
- [DELETE] /artwork/{id} 작품 삭제 API : 마지막 작품 삭제시 해당하는 전시까지 삭제하는 로직 추가
- 전시 삭제 메소드 ( ExhibitService.delete ) 의 소속된 작품, 태그까지 삭제하는지 확인하는 테스트 로직 추가
close #81
> 마지막 작품 삭제시 해당하는 전시까지 삭제하는 로직 추가

- src/main/java/com/yapp/artie/domain/archive/dto/cateogry/CategoryDto.java
- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
- src/main/java/com/yapp/artie/domain/user/controller/UserController.java
- src/main/java/com/yapp/artie/domain/user/service/UserService.java
- src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
- src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
- [PATCH] /user/{id} 닉네임 변경 API 
- API 추가
- [GET] /category 카테고리 목록 조회 API
- 해당 카테고리의 전시 수 필드 반환하도록 로직 및 필드 추가
close #102
> 닉네임 변경 API 추가 / 카테고리 목록 조회시 해당 카테고리의 전시 수 필드 반환

- src/main/java/com/yapp/artie/domain/user/controller/UserController.java
- src/main/java/com/yapp/artie/domain/user/service/UserService.java
- src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
- 유저 닉네임 변경 API에서 쿼리 변수 name을 내부적으로 path variable로 처리하려고 하여 발생하는 에러를 개선하였습니다.
close #102
> 유저 닉네임 변경 API 쿼리 변수 어노테이션 버그 개선

- src/main/java/com/yapp/artie/domain/archive/repository/ArtworkRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
- [DELETE] /artwork/{id} 작품 삭제 API
- 대표 작품 삭제시, 잔여 작품 중 가장 오래된 작품을 대표 작품으로 설정하는 로직 추가
close #81
> 작품 삭제 API의 대표 작품 삭제시 타 작품으로 설정되는 로직 추가

- src/main/java/com/yapp/artie/domain/archive/domain/artwork/Artwork.java
- src/main/java/com/yapp/artie/domain/archive/domain/category/Category.java
- src/main/java/com/yapp/artie/domain/archive/domain/exhibit/Exhibit.java
- src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
- src/main/java/com/yapp/artie/domain/user/controller/UserController.java
- src/main/java/com/yapp/artie/domain/user/domain/User.java
- src/main/java/com/yapp/artie/domain/user/service/UserService.java
- src/main/java/com/yapp/artie/global/exception/response/ErrorCode.java
- src/test/java/com/yapp/artie/BaseIntegrationTest.java
- src/test/java/com/yapp/artie/domain/archive/repository/CategoryRepositoryTest.java
- src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
- src/test/java/com/yapp/artie/domain/user/controller/UserControllerTest.java
- src/test/java/com/yapp/artie/domain/user/domain/UserTest.java
- src/test/java/com/yapp/artie/domain/user/repository/UserRepositoryTest.java
- src/test/java/com/yapp/artie/domain/user/service/UserServiceTest.java
- [DELETE] /user 유저 탈퇴 API : 버그 수정
- URI의 오타 수정 ( /user/ -> /user )
- jwtService를 UserService.delete 메소드의 파라미터로 받지 않도록 개선
- User 엔티티는 다른 엔티티와의 개인 소유 관계가 아니기 때문에, cascade 삭제가 부적합한 것으로 보여, 수동적으로 삭제하도록 개선
- 해당 유저의 카테고리 데이터를 먼저 삭제하고, 카테고리 삭제시 cascade 삭제로 전시, 작품, 태그가 삭제되도록 함
- 카테고리 데이터가 삭제된 이후, 유저 데이터를 삭제함
- 유저 API의 런칭 목적 authentication 처리 로직 교체
- 기존에는 개발상 편의를 위해 단순히 1L으로 처리하였음
- 런칭을 위해, 테스트 계정이 아닌 요청은 정상적으로 처리하도록 메소드 적용하여 처리
- 통합 테스트 base class 추가
- 테스트 상 편의를 위해, User 엔티티의 id를 입력하는 생성자 추가
- 테스트 상 편의를 위해, 테스트용 유저 정적 변수 선언
- Category Repository Unit Test 추가
- 유저 기반 카테고리를 삭제하는 CategoryRepository.deleteAllByUser메소드를 검증하는 레포지토리 테스트 추가
- 카테고리를 삭제하면 전시데이터도 삭제되는지에 대해, CategoryService.delete 메소드를 검증하는 테스트 추가
- 기존의 User Service Test를 단위 테스트로 처리하도록 변경
- UserService.updateUserName 메소드의 서비스 단위 테스트 추가
- 유저 …
> 유저 탈퇴시 정상적으로 데이터 삭제되지 않는 버그 개선 / 구조 개선 / 테스트 코드 추가 / 일부 authentication 처리 로직 개선

- src/main/java/com/yapp/artie/domain/archive/dto/exhibit/PostDetailInfo.java
- src/main/java/com/yapp/artie/domain/archive/service/ExhibitService.java
- src/test/java/com/yapp/artie/domain/archive/service/ExhibitServiceTest.java
아래 API의 PostDetailInfo DTO에 상단 고정 여부 필드 isPinned(boolean)를 추가함
- [GET] /post/home : 홈화면 전시 목록 조회
- [GET] /post/home/{id} : 홈화면 - 특정 카테고리 전시 목록 조회
- [GET] /post/detail/{id} : 전시 상세 정보 조회
close #112
> PostDetailInfo에 isPinned 필드 추가

- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
홈 화면 전시 조회에서 페이지네이션을 할 경우, last true가 제대로 출력이 안되는 버그가 있었음. 원인은 count 쿼리에서 isPublished가 누락 되어 발생했음.
수정하면서 다음 두 가지를 생각해봤는데, 의견이 궁금해요!
- Page와 Slice 두 종류의 타입이 있는데, Page를 사용하는 것이 적절한가?
- isPublished에 인덱스를 걸어야 하는가?
#122
> 전시 페이지네이션 카운트 쿼리 수정

- src/main/java/com/yapp/artie/domain/archive/repository/ExhibitRepository.java
페이지 네이션 카운트 쿼리에서 categoryId와 userId가 포함되어야 함
Reverts YAPP-Github/21st-ALL-Rounder-Team-2-BE#123
> Revert "전시 페이지네이션 카운트 쿼리 수정"

- src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetTestUserTokenController.java
- src/main/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseAuthenticationAdapter.java
- src/main/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseTokenGenerator.java
- src/main/java/com/yapp/artie/domain/user/application/port/in/GetTestUserTokenQuery.java
- src/main/java/com/yapp/artie/domain/user/application/port/in/GetTestUserTokenResponse.java
- src/main/java/com/yapp/artie/domain/user/application/port/out/GenerateTestTokenPort.java
- src/main/java/com/yapp/artie/domain/user/application/service/GetTestUserTokenService.java
- src/main/java/com/yapp/artie/global/config/SecurityConfig.java
- src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetTestUserTokenControllerTest.java
- src/test/java/com/yapp/artie/domain/user/adapter/out/authentication/FirebaseAuthenticationAdapterTest.java
- src/test/java/com/yapp/artie/domain/user/application/service/GetTestUserTokenServiceTest.java
- 테스트 유저 토큰 발급 API 추가
- Controller, Service, Query, Port 추가
- FirebaseAdapter 수정
- 테스트 유저 토큰 발급에 대한 테스트 추가
close #127
> 테스트 유저 토큰 발급 API 추가

- src/main/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateController.java
- src/main/java/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapter.java
- src/main/java/com/yapp/artie/domain/user/application/port/in/GetUserJoinDateQuery.java
- src/main/java/com/yapp/artie/domain/user/application/port/in/GetUserJoinDateResponse.java
- src/main/java/com/yapp/artie/domain/user/application/port/out/LoadUserPort.java
- src/main/java/com/yapp/artie/domain/user/application/service/GetUserJoinDateService.java
- src/test/java/com/yapp/artie/domain/user/adapter/in/web/GetUserJoinDateControllerTest.java
- src/test/java/com/yapp/artie/domain/user/adapter/out/persistence/UserPersistenceAdapterTest.java
- src/test/java/com/yapp/artie/domain/user/application/service/GetUserJoinDateServiceTest.java
- 유저 조회 API 추가
- 컨트롤러, 서비스, Response, Query 추가
- LoadUserPort 인터페이스에 loadUserJoinDate 메소드 추가
- UserPersistenceAdapter 클래스에 loadUserJoinDate 메소드 추가
close #131
> 유저 조회 API 추가

- src/main/java/com/yapp/artie/domain/archive/service/ArtworkService.java
- src/test/java/com/yapp/artie/domain/archive/service/ArtworkServiceTest.java
- 이미 대표 작품으로 설정되어 있는 작품에 대해 대표 작품 등록을 요청할 경우, 대표 설정이 해제되는 버그 해결
- 이미 대표 작품으로 설정되어 있을 경우, 추가적인 로직을 수행하지 않도록 처리함
```java
@Transactional
public void setMainArtwork(Long artworkId, Long userId) {
Artwork artwork = findById(artworkId, userId); //1
artworkRepository.updateArtworkNotMainByExhibit( artwork.getExhibit()); //2
artwork.setMainArtwork(); //3
}
```
위 코드는 대표 작품으로 설정하는 서비스 메소드입니다.
주어진 작품 ID를 통해 작품을 찾고(1), 
해당 작품으로 부터 전시를 확인해 그 전시에 등록된 작품 중 대표 작품으로 등록되어있던 작품을 대표 설정 해제 하고(2),
주어진 작품은 대표 작품으로 설정합니다. (3)
더 자세하게 쿼리와 영속성 컨텍스트 방면에서 설명하도록 하겠습니다.
1. 주어진 작품을 찾습니다.
2. `artworkRepository.updateArtworkNotMainByExhibit` 메소드를 통해, 기존에 등록된 대표 작품을 대표 해제하는 벌크성 쿼리를 수행합니다.
1. 벌크성 쿼리는 즉시 실행되며, 이후에 영속성 컨텍스를 flush합니다.
2. 벌크성 쿼리는 즉시 실행되므로, 주어진 작품은 이제 **DB 상에서는** 대표 해제, 즉 isMain = false 값을 가집니다.
3. …
> 이미 대표 작품으로 설정되어 있는 작품에 대해 대표 작품 등록을 요청할 경우, 대표 설정이 해제되는 버그 해결

- src/main/java/com/yapp/artie/domain/archive/repository/CategoryRepository.java
- src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
- src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
- [PUT] /category/sequence 요청시, Request Body로 넘겨주는 CategoryDto에 sequence값을 변경된 순서값으로 넘겨줘 index out of error가 발생함
- 기존 로직은, Request Body에 넘겨주는 CategoryDto에 넘겨주는 sequence 값이 기존의 값이며, 변경된 배열의 순서는 Request Body에 담긴 배열 내의 CategoryDto 순서를 바탕으로 순서를 조정하였음
- 따라서, Request Body로 넘겨주는 CategoryDto에 sequence값을 변경된 순서값으로 받도록 처리함
close #136
> 카테고리 순서 변경 불가 버그 수정

- src/main/java/com/yapp/artie/domain/archive/service/CategoryService.java
- src/test/java/com/yapp/artie/domain/archive/service/CategoryServiceTest.java
- [GET] /category : 카테고리 목록 조회
- 기존 로직은 사용자의 카테고리가 존재하지 않다면 404 에러를 발생
- emptyList를 반환하도록 기능 수정
#143
> 카테고리 목록 조회시, 카테고리가 없으면 404 에러 발생
